name: Lint Go

on:
  push:
    branches:
      - dev*
    paths:
      - "**.go"
      - ".github/workflows/lint_go.yml"
  pull_request:
    branches:
      - dev*
    paths:
      - "**.go"
      - ".github/workflows/lint_go.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Golang Version
        id: version
        run: |
          source buildScript/init/version.sh
          echo go_version=$GO_VERSION >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          cache-dependency-path: libcore/go.sum
      - uses: golangci/golangci-lint-action@v5
        with:
          skip-cache: true
          working-directory: ./libcore/
          version: latest
          args: --timeout=30m --config="./.golangci.yml"
          install-mode: binary
      - name: Run Test
        run: |
          make test_go
